### ISSUE TITLE
v8.2 release

### ISSUE THREAD

**Issue by mshick** [aptible/docker-nodejs#29]
I've been trying to update my app to use Node 8. Unfortunately, I've been bitten by this bug in the 8.1 line: https://github.com/nodejs/node/issues/13325, and the node team says it was fixed in the 8.2 release here: https://github.com/nodejs/node/issues/14198.

I know 8.2 hasn't been out long, just want you to know there's an Aptible customer out there who could use it.

**Comment by fancyremarker** [comment]
Hi @mshick , sure thing: just added. You can also use the standard Docker library image in a case like this. For example: `FROM node:8.2.1-wheezy`.

**Comment by mshick** [comment]
@fancyremarker Can you unpack that a little more? 

Are you saying I could use a standard Node image for my Dockerfile and Aptible container deploys? Would there be any security implications to using the standard Node image vs Aptible's?

**Comment by fancyremarker** [comment]
Hi @mshick : there's no specific security (or compliance) disadvantage to using the library Node image instead of Aptible's image. Historically, we have only supported our own images because corresponding library Node images did not always exist (i.e., Aptible is older 👵 than much of the Docker image library). In fact, we now recommend the library `node` image in our Node and Express Quickstart guides.

The best thing you can do to maintain a strong security posture with respect to your apps' Docker images is to make vulnerability scanning a part of your process — starting, e.g., with the built-in image vulnerability scanning that Aptible provides. My colleague @krallin wrote about vulnerability scanning for image dependencies [here](https://www.aptible.com/blog/vulnerability-scanning-for-your-dependencies-why-and-how/); I think that's a good starting point for developing a secure process for your apps' Docker images.

**Comment by mshick** [comment]
@fancyremarker great, thanks, I'll move onto the standard Node images then. I appreciate the thorough response!
